// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

type AssetUpdateEventSchema struct {

	// The 'asset' Field.
	Asset Asset `json:"asset"`

	// The 'assetName' Field.
	AssetName string `json:"assetName"`
}
