// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

type AssetSpecificationSchema struct {

	// The 'assetTypeRefs' Field.
	AssetTypeRefs []string `json:"assetTypeRefs,omitempty"`

	// The 'attributes' Field.
	Attributes map[string]string `json:"attributes,omitempty"`

	// The 'datasets' Field.
	Datasets []AssetDatasetSchemaElementSchema `json:"datasets,omitempty"`

	// The 'defaultDatasetsConfiguration' Field.
	DefaultDatasetsConfiguration *string `json:"defaultDatasetsConfiguration,omitempty"`

	// The 'defaultDatasetsDestinations' Field.
	DefaultDatasetsDestinations []DefaultDatasetsDestinationsSchemaElementSchema `json:"defaultDatasetsDestinations,omitempty"`

	// The 'defaultEventsConfiguration' Field.
	DefaultEventsConfiguration *string `json:"defaultEventsConfiguration,omitempty"`

	// The 'defaultEventsDestinations' Field.
	DefaultEventsDestinations []DefaultEventsDestinationsSchemaElementSchema `json:"defaultEventsDestinations,omitempty"`

	// The 'defaultManagementGroupsConfiguration' Field.
	DefaultManagementGroupsConfiguration *string `json:"defaultManagementGroupsConfiguration,omitempty"`

	// The 'defaultStreamsConfiguration' Field.
	DefaultStreamsConfiguration *string `json:"defaultStreamsConfiguration,omitempty"`

	// The 'defaultStreamsDestinations' Field.
	DefaultStreamsDestinations []DefaultStreamsDestinationsSchemaElementSchema `json:"defaultStreamsDestinations,omitempty"`

	// The 'description' Field.
	Description *string `json:"description,omitempty"`

	// The 'deviceRef' Field.
	DeviceRef DeviceRefSchema `json:"deviceRef"`

	// The 'discoveredAssetRefs' Field.
	DiscoveredAssetRefs []string `json:"discoveredAssetRefs,omitempty"`

	// The 'displayName' Field.
	DisplayName *string `json:"displayName,omitempty"`

	// The 'documentationUri' Field.
	DocumentationUri *string `json:"documentationUri,omitempty"`

	// The 'enabled' Field.
	Enabled *bool `json:"enabled,omitempty"`

	// The 'events' Field.
	Events []AssetEventSchemaElementSchema `json:"events,omitempty"`

	// The 'externalAssetId' Field.
	ExternalAssetId *string `json:"externalAssetId,omitempty"`

	// The 'hardwareRevision' Field.
	HardwareRevision *string `json:"hardwareRevision,omitempty"`

	// The 'lastTransitionTime' Field.
	LastTransitionTime *string `json:"lastTransitionTime,omitempty"`

	// The 'managementGroups' Field.
	ManagementGroups []AssetManagementGroupSchemaElementSchema `json:"managementGroups,omitempty"`

	// The 'manufacturer' Field.
	Manufacturer *string `json:"manufacturer,omitempty"`

	// The 'manufacturerUri' Field.
	ManufacturerUri *string `json:"manufacturerUri,omitempty"`

	// The 'model' Field.
	Model *string `json:"model,omitempty"`

	// The 'productCode' Field.
	ProductCode *string `json:"productCode,omitempty"`

	// The 'serialNumber' Field.
	SerialNumber *string `json:"serialNumber,omitempty"`

	// The 'softwareRevision' Field.
	SoftwareRevision *string `json:"softwareRevision,omitempty"`

	// The 'streams' Field.
	Streams []AssetStreamSchemaElementSchema `json:"streams,omitempty"`

	// The 'uuid' Field.
	Uuid *string `json:"uuid,omitempty"`

	// The 'version' Field.
	Version *uint64 `json:"version,omitempty"`
}
