// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

type AssetStreamSchemaElementSchema struct {

	// The 'destinations' Field.
	Destinations []AssetStreamDestinationSchemaElementSchema `json:"destinations,omitempty"`

	// The 'name' Field.
	Name string `json:"name"`

	// The 'streamConfiguration' Field.
	StreamConfiguration *string `json:"streamConfiguration,omitempty"`

	// The 'typeRef' Field.
	TypeRef *string `json:"typeRef,omitempty"`
}
