// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

type AssetUpdateEventTelemetry struct {

	// The 'assetUpdateEvent' Telemetry.
	AssetUpdateEvent AssetUpdateEventSchema `json:"assetUpdateEvent"`
}
