// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

type AssetEndpointProfileStatus struct {

	// The 'errors' Field.
	Errors []Error `json:"errors,omitempty"`
}
