// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

import (
	"encoding/json"
	"errors"
)

type AssetDataPointObservabilityModeSchema int32

const (
	Counter AssetDataPointObservabilityModeSchema = iota
	Gauge AssetDataPointObservabilityModeSchema = iota
	Histogram AssetDataPointObservabilityModeSchema = iota
	Log AssetDataPointObservabilityModeSchema = iota
	None AssetDataPointObservabilityModeSchema = iota
)

func (v AssetDataPointObservabilityModeSchema) String() string {
	switch v {
	case Counter:
		return "Counter"
	case Gauge:
		return "Gauge"
	case Histogram:
		return "Histogram"
	case Log:
		return "Log"
	case None:
		return "None"
	default:
		return ""
	}
}

func (v AssetDataPointObservabilityModeSchema) MarshalJSON() ([]byte, error) {
	var s string
	switch v {
	case Counter:
		s = "Counter"
	case Gauge:
		s = "Gauge"
	case Histogram:
		s = "Histogram"
	case Log:
		s = "Log"
	case None:
		s = "None"
	default:
		return []byte{}, errors.New("unable to marshal unrecognized enum value to JSON")
	}

	return json.Marshal(s)
}

func (v *AssetDataPointObservabilityModeSchema) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}

	switch s {
	case "Counter":
		*v = Counter
	case "Gauge":
		*v = Gauge
	case "Histogram":
		*v = Histogram
	case "Log":
		*v = Log
	case "None":
		*v = None
	default:
		return errors.New("unable to unmarshal unrecognized enum value from JSON")
	}

	return nil
}
