// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

type Asset struct {

	// The 'name' Field.
	Name string `json:"name"`

	// The 'specification' Field.
	Specification AssetSpecificationSchema `json:"specification"`

	// The 'status' Field.
	Status *AssetStatus `json:"status,omitempty"`
}
