// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

type AssetManagementGroupStatusSchemaElementSchema struct {

	// The 'actions' Field.
	Actions []AssetManagementGroupActionStatusSchemaElementSchema `json:"actions,omitempty"`

	// The 'name' Field.
	Name string `json:"name"`
}
