// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

type AssetEndpointProfileSpecificationSchema struct {

	// The 'additionalConfiguration' Field.
	AdditionalConfiguration *string `json:"additionalConfiguration,omitempty"`

	// The 'authentication' Field.
	Authentication *AuthenticationSchema `json:"authentication,omitempty"`

	// The 'discoveredAssetEndpointProfileRef' Field.
	DiscoveredAssetEndpointProfileRef *string `json:"discoveredAssetEndpointProfileRef,omitempty"`

	// The 'endpointProfileType' Field.
	EndpointProfileType string `json:"endpointProfileType"`

	// The 'targetAddress' Field.
	TargetAddress string `json:"targetAddress"`

	// The 'uuid' Field.
	Uuid *string `json:"uuid,omitempty"`
}
