// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

type AssetManagementGroupActionStatusSchemaElementSchema struct {

	// The 'error' Field.
	Error *ConfigError `json:"error,omitempty"`

	// The 'name' Field.
	Name string `json:"name"`

	// The 'requestMessageSchemaReference' Field.
	RequestMessageSchemaReference *MessageSchemaReference `json:"requestMessageSchemaReference,omitempty"`

	// The 'responseMessageSchemaReference' Field.
	ResponseMessageSchemaReference *MessageSchemaReference `json:"responseMessageSchemaReference,omitempty"`
}
