// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

import (
	"encoding/json"
	"errors"
)

type AssetManagementGroupActionTypeSchema int32

const (
	AssetManagementGroupActionTypeSchemaCall AssetManagementGroupActionTypeSchema = iota
	AssetManagementGroupActionTypeSchemaRead AssetManagementGroupActionTypeSchema = iota
	AssetManagementGroupActionTypeSchemaWrite AssetManagementGroupActionTypeSchema = iota
)

func (v AssetManagementGroupActionTypeSchema) String() string {
	switch v {
	case AssetManagementGroupActionTypeSchemaCall:
		return "Call"
	case AssetManagementGroupActionTypeSchemaRead:
		return "Read"
	case AssetManagementGroupActionTypeSchemaWrite:
		return "Write"
	default:
		return ""
	}
}

func (v AssetManagementGroupActionTypeSchema) MarshalJSON() ([]byte, error) {
	var s string
	switch v {
	case AssetManagementGroupActionTypeSchemaCall:
		s = "Call"
	case AssetManagementGroupActionTypeSchemaRead:
		s = "Read"
	case AssetManagementGroupActionTypeSchemaWrite:
		s = "Write"
	default:
		return []byte{}, errors.New("unable to marshal unrecognized enum value to JSON")
	}

	return json.Marshal(s)
}

func (v *AssetManagementGroupActionTypeSchema) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}

	switch s {
	case "Call":
		*v = AssetManagementGroupActionTypeSchemaCall
	case "Read":
		*v = AssetManagementGroupActionTypeSchemaRead
	case "Write":
		*v = AssetManagementGroupActionTypeSchemaWrite
	default:
		return errors.New("unable to unmarshal unrecognized enum value from JSON")
	}

	return nil
}
