// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

type AssetSpecificationSchema struct {

	// The 'assetEndpointProfileRef' Field.
	AssetEndpointProfileRef string `json:"assetEndpointProfileRef"`

	// The 'attributes' Field.
	Attributes map[string]string `json:"attributes,omitempty"`

	// The 'datasets' Field.
	Datasets []AssetDatasetSchemaElementSchema `json:"datasets,omitempty"`

	// The 'defaultDatasetsConfiguration' Field.
	DefaultDatasetsConfiguration *string `json:"defaultDatasetsConfiguration,omitempty"`

	// The 'defaultEventsConfiguration' Field.
	DefaultEventsConfiguration *string `json:"defaultEventsConfiguration,omitempty"`

	// The 'defaultTopic' Field.
	DefaultTopic *Topic `json:"defaultTopic,omitempty"`

	// The 'description' Field.
	Description *string `json:"description,omitempty"`

	// The 'discoveredAssetRefs' Field.
	DiscoveredAssetRefs []string `json:"discoveredAssetRefs,omitempty"`

	// The 'displayName' Field.
	DisplayName *string `json:"displayName,omitempty"`

	// The 'documentationUri' Field.
	DocumentationUri *string `json:"documentationUri,omitempty"`

	// The 'enabled' Field.
	Enabled *bool `json:"enabled,omitempty"`

	// The 'events' Field.
	Events []AssetEventSchemaElementSchema `json:"events,omitempty"`

	// The 'externalAssetId' Field.
	ExternalAssetId *string `json:"externalAssetId,omitempty"`

	// The 'hardwareRevision' Field.
	HardwareRevision *string `json:"hardwareRevision,omitempty"`

	// The 'manufacturer' Field.
	Manufacturer *string `json:"manufacturer,omitempty"`

	// The 'manufacturerUri' Field.
	ManufacturerUri *string `json:"manufacturerUri,omitempty"`

	// The 'model' Field.
	Model *string `json:"model,omitempty"`

	// The 'productCode' Field.
	ProductCode *string `json:"productCode,omitempty"`

	// The 'serialNumber' Field.
	SerialNumber *string `json:"serialNumber,omitempty"`

	// The 'softwareRevision' Field.
	SoftwareRevision *string `json:"softwareRevision,omitempty"`

	// The 'uuid' Field.
	Uuid *string `json:"uuid,omitempty"`

	// The 'version' Field.
	Version *string `json:"version,omitempty"`
}
