// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

type AssetEndpointProfile struct {

	// The 'name' Field.
	Name string `json:"name"`

	// The 'specification' Field.
	Specification AssetEndpointProfileSpecificationSchema `json:"specification"`

	// The 'status' Field.
	Status *AssetEndpointProfileStatus `json:"status,omitempty"`
}
