// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

type AssetEndpointProfileUpdateEventTelemetry struct {

	// The 'assetEndpointProfileUpdateEvent' Telemetry.
	AssetEndpointProfileUpdateEvent AssetEndpointProfileUpdateEventSchema `json:"assetEndpointProfileUpdateEvent"`
}
