// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

type AssetManagementGroupActionSchemaElementSchema struct {

	// The 'actionConfiguration' Field.
	ActionConfiguration *string `json:"actionConfiguration,omitempty"`

	// The 'actionType' Field.
	ActionType AssetManagementGroupActionTypeSchema `json:"actionType"`

	// The 'name' Field.
	Name string `json:"name"`

	// The 'targetUri' Field.
	TargetUri string `json:"targetUri"`

	// The 'timeOutInSeconds' Field.
	TimeOutInSeconds *uint32 `json:"timeOutInSeconds,omitempty"`

	// The 'topic' Field.
	Topic *string `json:"topic,omitempty"`

	// The 'typeRef' Field.
	TypeRef *string `json:"typeRef,omitempty"`
}
