// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

type AuthenticationSchema struct {

	// The 'method' Field.
	Method MethodSchema `json:"method"`

	// The 'usernamePasswordCredentials' Field.
	UsernamePasswordCredentials *UsernamePasswordCredentialsSchema `json:"usernamePasswordCredentials,omitempty"`

	// The 'x509Credentials' Field.
	X509credentials *X509credentialsSchema `json:"x509Credentials,omitempty"`
}
