// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

type ConfigError struct {

	// The 'code' Field.
	Code *string `json:"code,omitempty"`

	// The 'details' Field.
	Details []DetailsSchemaElementSchema `json:"details,omitempty"`

	// The 'innerError' Field.
	InnerError map[string]string `json:"innerError,omitempty"`

	// The 'message' Field.
	Message *string `json:"message,omitempty"`
}
