// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

import (
	"context"

	"github.com/Azure/iot-operations-sdks/go/protocol"
)

type CreateDetectedAssetCommandInvoker struct {
	*protocol.CommandInvoker[CreateDetectedAssetRequestPayload, CreateDetectedAssetResponsePayload]
}

func NewCreateDetectedAssetCommandInvoker(
	app *protocol.Application,
	client protocol.MqttClient,
	requestTopic string,
	opt ...protocol.CommandInvokerOption,
) (*CreateDetectedAssetCommandInvoker, error) {
	var err error
	invoker := &CreateDetectedAssetCommandInvoker{}

	var opts protocol.CommandInvokerOptions
	opts.Apply(
		opt,
		protocol.WithTopicTokens{
			"commandName": "createDetectedAsset",
		},
	)

	invoker.CommandInvoker, err = protocol.NewCommandInvoker(
		app,
		client,
		protocol.JSON[CreateDetectedAssetRequestPayload]{},
		protocol.JSON[CreateDetectedAssetResponsePayload]{},
		requestTopic,
		&opts,
	)

	return invoker, err
}

func (invoker CreateDetectedAssetCommandInvoker) CreateDetectedAsset(
	ctx context.Context,
	request CreateDetectedAssetRequestPayload,
	opt ...protocol.InvokeOption,
) (*protocol.CommandResponse[CreateDetectedAssetResponsePayload], error) {
	invokerOpts := []protocol.InvokeOption{
		protocol.WithTopicTokenNamespace("ex:"),
	}

	var invokeOpts protocol.InvokeOptions
	invokeOpts.Apply(opt, invokerOpts...)

	response, err := invoker.Invoke(
		ctx,
		request,
		&invokeOpts,
	)

	return response, err
}
