// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

type CreateDetectedAssetRequestPayload struct {

	// The Command request argument.
	DetectedAsset DetectedAsset `json:"detectedAsset"`
}
