// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

type CreateDetectedAssetResponseSchema struct {

	// status of detected asset creation
	Status DetectedAssetResponseStatusSchema `json:"status"`
}
