// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

type DefaultEventsDestinationsSchemaElementSchema struct {

	// The 'configuration' Field.
	Configuration DestinationConfiguration `json:"configuration"`

	// The 'target' Field.
	Target EventStreamTarget `json:"target"`
}
