// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

type DetailsSchemaElementSchema struct {

	// The 'code' Field.
	Code *string `json:"code,omitempty"`

	// The 'correlationId' Field.
	CorrelationId *string `json:"correlationId,omitempty"`

	// The 'info' Field.
	Info *string `json:"info,omitempty"`

	// The 'message' Field.
	Message *string `json:"message,omitempty"`
}
