// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

type DetectedAssetEventSchemaElementSchema struct {

	// The 'eventConfiguration' Field.
	EventConfiguration *string `json:"eventConfiguration,omitempty"`

	// The 'eventNotifier' Field.
	EventNotifier string `json:"eventNotifier"`

	// The 'lastUpdatedOn' Field.
	LastUpdatedOn *string `json:"lastUpdatedOn,omitempty"`

	// The 'name' Field.
	Name string `json:"name"`

	// The 'topic' Field.
	Topic *Topic `json:"topic,omitempty"`
}
