// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

type DetectedAssetDataPointSchemaElementSchema struct {

	// The 'dataPointConfiguration' Field.
	DataPointConfiguration *string `json:"dataPointConfiguration,omitempty"`

	// The 'dataSource' Field.
	DataSource string `json:"dataSource"`

	// The 'lastUpdatedOn' Field.
	LastUpdatedOn *string `json:"lastUpdatedOn,omitempty"`

	// The 'name' Field.
	Name *string `json:"name,omitempty"`
}
