// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

import (
	"encoding/json"
	"errors"
)

type DetectedAssetResponseStatusSchema int32

const (
	DetectedAssetResponseStatusSchemaCreated DetectedAssetResponseStatusSchema = iota
	DetectedAssetResponseStatusSchemaDuplicate DetectedAssetResponseStatusSchema = iota
	DetectedAssetResponseStatusSchemaFailed DetectedAssetResponseStatusSchema = iota
)

func (v DetectedAssetResponseStatusSchema) String() string {
	switch v {
	case DetectedAssetResponseStatusSchemaCreated:
		return "Created"
	case DetectedAssetResponseStatusSchemaDuplicate:
		return "Duplicate"
	case DetectedAssetResponseStatusSchemaFailed:
		return "Failed"
	default:
		return ""
	}
}

func (v DetectedAssetResponseStatusSchema) MarshalJSON() ([]byte, error) {
	var s string
	switch v {
	case DetectedAssetResponseStatusSchemaCreated:
		s = "created"
	case DetectedAssetResponseStatusSchemaDuplicate:
		s = "duplicate"
	case DetectedAssetResponseStatusSchemaFailed:
		s = "failed"
	default:
		return []byte{}, errors.New("unable to marshal unrecognized enum value to JSON")
	}

	return json.Marshal(s)
}

func (v *DetectedAssetResponseStatusSchema) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}

	switch s {
	case "created":
		*v = DetectedAssetResponseStatusSchemaCreated
	case "duplicate":
		*v = DetectedAssetResponseStatusSchemaDuplicate
	case "failed":
		*v = DetectedAssetResponseStatusSchemaFailed
	default:
		return errors.New("unable to unmarshal unrecognized enum value from JSON")
	}

	return nil
}
