// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

import (
	"github.com/Azure/iot-operations-sdks/go/protocol"
)

type DeviceUpdateEventTelemetryReceiver struct {
	*protocol.TelemetryReceiver[DeviceUpdateEventTelemetry]
}

func NewDeviceUpdateEventTelemetryReceiver(
	app *protocol.Application,
	client protocol.MqttClient,
	topic string,
	handler protocol.TelemetryHandler[DeviceUpdateEventTelemetry],
	opt ...protocol.TelemetryReceiverOption,
) (*DeviceUpdateEventTelemetryReceiver, error) {
	var err error
	receiver := &DeviceUpdateEventTelemetryReceiver{}

	var opts protocol.TelemetryReceiverOptions
	opts.Apply(
		opt,
		protocol.WithTopicTokens{
			"telemetryName":     "deviceUpdateEvent",
		},
	)

	receiver.TelemetryReceiver, err = protocol.NewTelemetryReceiver(
		app,
		client,
		protocol.JSON[DeviceUpdateEventTelemetry]{},
		topic,
		handler,
		&opts,
	)

	return receiver, err
}
