// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

type DeviceStatusEndpointSchema struct {

	// The 'inbound' Field.
	Inbound map[string]DeviceStatusInboundEndpointSchemaMapValueSchema `json:"inbound,omitempty"`
}
