// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

type DeviceUpdateEventTelemetry struct {

	// The 'deviceUpdateEvent' Telemetry.
	DeviceUpdateEvent DeviceUpdateEventSchema `json:"deviceUpdateEvent"`
}
