// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

type DeviceEndpointSchema struct {

	// The 'inbound' Field.
	Inbound map[string]InboundSchemaMapValueSchema `json:"inbound,omitempty"`

	// The 'outbound' Field.
	Outbound *OutboundSchema `json:"outbound,omitempty"`
}
