// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

type DeviceStatusConfigSchema struct {

	// The 'error' Field.
	Error *ConfigError `json:"error,omitempty"`

	// The 'lastTransitionTime' Field.
	LastTransitionTime *string `json:"lastTransitionTime,omitempty"`

	// The 'version' Field.
	Version *uint64 `json:"version,omitempty"`
}
