// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

type DeviceStatus struct {

	// The 'config' Field.
	Config *DeviceStatusConfigSchema `json:"config,omitempty"`

	// The 'endpoints' Field.
	Endpoints *DeviceStatusEndpointSchema `json:"endpoints,omitempty"`
}
