// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

type DeviceRefSchema struct {

	// The 'deviceName' Field.
	DeviceName string `json:"deviceName"`

	// The 'endpointName' Field.
	EndpointName string `json:"endpointName"`
}
