// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

type Error struct {

	// The 'code' Field.
	Code *int32 `json:"code,omitempty"`

	// The 'message' Field.
	Message *string `json:"message,omitempty"`
}
