// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

import (
	"encoding/json"
	"errors"
)

type EventStreamTarget int32

const (
	EventStreamTargetMqtt EventStreamTarget = iota
	EventStreamTargetStorage EventStreamTarget = iota
)

func (v EventStreamTarget) String() string {
	switch v {
	case EventStreamTargetMqtt:
		return "Mqtt"
	case EventStreamTargetStorage:
		return "Storage"
	default:
		return ""
	}
}

func (v EventStreamTarget) MarshalJSON() ([]byte, error) {
	var s string
	switch v {
	case EventStreamTargetMqtt:
		s = "Mqtt"
	case EventStreamTargetStorage:
		s = "Storage"
	default:
		return []byte{}, errors.New("unable to marshal unrecognized enum value to JSON")
	}

	return json.Marshal(s)
}

func (v *EventStreamTarget) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}

	switch s {
	case "Mqtt":
		*v = EventStreamTargetMqtt
	case "Storage":
		*v = EventStreamTargetStorage
	default:
		return errors.New("unable to unmarshal unrecognized enum value from JSON")
	}

	return nil
}
