// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

import (
	"encoding/json"
	"errors"
)

type EventType int32

const (
	Create EventType = iota
	Delete EventType = iota
	Update EventType = iota
)

func (v EventType) String() string {
	switch v {
	case Create:
		return "Create"
	case Delete:
		return "Delete"
	case Update:
		return "Update"
	default:
		return ""
	}
}

func (v EventType) MarshalJSON() ([]byte, error) {
	var s string
	switch v {
	case Create:
		s = "Create"
	case Delete:
		s = "Delete"
	case Update:
		s = "Update"
	default:
		return []byte{}, errors.New("unable to marshal unrecognized enum value to JSON")
	}

	return json.Marshal(s)
}

func (v *EventType) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}

	switch s {
	case "Create":
		*v = Create
	case "Delete":
		*v = Delete
	case "Update":
		*v = Update
	default:
		return errors.New("unable to unmarshal unrecognized enum value from JSON")
	}

	return nil
}
