// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

import (
	"context"

	"github.com/Azure/iot-operations-sdks/go/protocol"
)

type GetAssetCommandInvoker struct {
	*protocol.CommandInvoker[GetAssetRequestPayload, GetAssetResponsePayload]
}

func NewGetAssetCommandInvoker(
	app *protocol.Application,
	client protocol.MqttClient,
	requestTopic string,
	opt ...protocol.CommandInvokerOption,
) (*GetAssetCommandInvoker, error) {
	var err error
	invoker := &GetAssetCommandInvoker{}

	var opts protocol.CommandInvokerOptions
	opts.Apply(
		opt,
		protocol.WithTopicTokens{
			"commandName": "getAsset",
		},
	)

	invoker.CommandInvoker, err = protocol.NewCommandInvoker(
		app,
		client,
		protocol.JSON[GetAssetRequestPayload]{},
		protocol.JSON[GetAssetResponsePayload]{},
		requestTopic,
		&opts,
	)

	return invoker, err
}

func (invoker GetAssetCommandInvoker) GetAsset(
	ctx context.Context,
	request GetAssetRequestPayload,
	opt ...protocol.InvokeOption,
) (*protocol.CommandResponse[GetAssetResponsePayload], error) {
	invokerOpts := []protocol.InvokeOption{
		protocol.WithTopicTokenNamespace("ex:"),
	}

	var invokeOpts protocol.InvokeOptions
	invokeOpts.Apply(opt, invokerOpts...)

	response, err := invoker.Invoke(
		ctx,
		request,
		&invokeOpts,
	)

	return response, err
}
