// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

import (
	"context"

	"github.com/Azure/iot-operations-sdks/go/protocol"
)

type GetDeviceCommandInvoker struct {
	*protocol.CommandInvoker[any, GetDeviceResponsePayload]
}

func NewGetDeviceCommandInvoker(
	app *protocol.Application,
	client protocol.MqttClient,
	requestTopic string,
	opt ...protocol.CommandInvokerOption,
) (*GetDeviceCommandInvoker, error) {
	var err error
	invoker := &GetDeviceCommandInvoker{}

	var opts protocol.CommandInvokerOptions
	opts.Apply(
		opt,
		protocol.WithTopicTokens{
			"commandName": "getDevice",
		},
	)

	invoker.CommandInvoker, err = protocol.NewCommandInvoker(
		app,
		client,
		protocol.Empty{},
		protocol.JSON[GetDeviceResponsePayload]{},
		requestTopic,
		&opts,
	)

	return invoker, err
}

func (invoker GetDeviceCommandInvoker) GetDevice(
	ctx context.Context,
	opt ...protocol.InvokeOption,
) (*protocol.CommandResponse[GetDeviceResponsePayload], error) {
	invokerOpts := []protocol.InvokeOption{
		protocol.WithTopicTokenNamespace("ex:"),
	}

	var invokeOpts protocol.InvokeOptions
	invokeOpts.Apply(opt, invokerOpts...)

	response, err := invoker.Invoke(
		ctx,
		nil,
		&invokeOpts,
	)

	return response, err
}
