// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

type GetAssetRequestPayload struct {

	// The Command request argument.
	AssetName string `json:"assetName"`
}
