// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

type MessageSchemaReference struct {

	// The 'schemaName' Field.
	SchemaName string `json:"schemaName"`

	// The 'schemaNamespace' Field.
	SchemaNamespace string `json:"schemaNamespace"`

	// The 'schemaVersion' Field.
	SchemaVersion string `json:"schemaVersion"`
}
