// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

import (
	"encoding/json"
	"errors"
)

type MethodSchema int32

const (
	MethodSchemaAnonymous MethodSchema = iota
	MethodSchemaCertificate MethodSchema = iota
	MethodSchemaUsernamePassword MethodSchema = iota
)

func (v MethodSchema) String() string {
	switch v {
	case MethodSchemaAnonymous:
		return "Anonymous"
	case MethodSchemaCertificate:
		return "Certificate"
	case MethodSchemaUsernamePassword:
		return "UsernamePassword"
	default:
		return ""
	}
}

func (v MethodSchema) MarshalJSON() ([]byte, error) {
	var s string
	switch v {
	case MethodSchemaAnonymous:
		s = "Anonymous"
	case MethodSchemaCertificate:
		s = "Certificate"
	case MethodSchemaUsernamePassword:
		s = "UsernamePassword"
	default:
		return []byte{}, errors.New("unable to marshal unrecognized enum value to JSON")
	}

	return json.Marshal(s)
}

func (v *MethodSchema) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}

	switch s {
	case "Anonymous":
		*v = MethodSchemaAnonymous
	case "Certificate":
		*v = MethodSchemaCertificate
	case "UsernamePassword":
		*v = MethodSchemaUsernamePassword
	default:
		return errors.New("unable to unmarshal unrecognized enum value from JSON")
	}

	return nil
}
