// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

type NotifyOnAssetEndpointProfileUpdateRequestPayload struct {

	// The Command request argument.
	NotificationRequest NotificationMessageType `json:"notificationRequest"`
}
