// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

import (
	"context"

	"github.com/Azure/iot-operations-sdks/go/protocol"
)

type NotifyOnAssetEndpointProfileUpdateCommandInvoker struct {
	*protocol.CommandInvoker[NotifyOnAssetEndpointProfileUpdateRequestPayload, NotifyOnAssetEndpointProfileUpdateResponsePayload]
}

func NewNotifyOnAssetEndpointProfileUpdateCommandInvoker(
	app *protocol.Application,
	client protocol.MqttClient,
	requestTopic string,
	opt ...protocol.CommandInvokerOption,
) (*NotifyOnAssetEndpointProfileUpdateCommandInvoker, error) {
	var err error
	invoker := &NotifyOnAssetEndpointProfileUpdateCommandInvoker{}

	var opts protocol.CommandInvokerOptions
	opts.Apply(
		opt,
		protocol.WithTopicTokens{
			"commandName": "notifyOnAssetEndpointProfileUpdate",
		},
	)

	invoker.CommandInvoker, err = protocol.NewCommandInvoker(
		app,
		client,
		protocol.JSON[NotifyOnAssetEndpointProfileUpdateRequestPayload]{},
		protocol.JSON[NotifyOnAssetEndpointProfileUpdateResponsePayload]{},
		requestTopic,
		&opts,
	)

	return invoker, err
}

func (invoker NotifyOnAssetEndpointProfileUpdateCommandInvoker) NotifyOnAssetEndpointProfileUpdate(
	ctx context.Context,
	request NotifyOnAssetEndpointProfileUpdateRequestPayload,
	opt ...protocol.InvokeOption,
) (*protocol.CommandResponse[NotifyOnAssetEndpointProfileUpdateResponsePayload], error) {
	invokerOpts := []protocol.InvokeOption{
		protocol.WithTopicTokenNamespace("ex:"),
	}

	var invokeOpts protocol.InvokeOptions
	invokeOpts.Apply(opt, invokerOpts...)

	response, err := invoker.Invoke(
		ctx,
		request,
		&invokeOpts,
	)

	return response, err
}
