// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

import (
	"encoding/json"
	"errors"
)

type NotificationResponse int32

const (
	Accepted NotificationResponse = iota
	Failed NotificationResponse = iota
)

func (v NotificationResponse) String() string {
	switch v {
	case Accepted:
		return "Accepted"
	case Failed:
		return "Failed"
	default:
		return ""
	}
}

func (v NotificationResponse) MarshalJSON() ([]byte, error) {
	var s string
	switch v {
	case Accepted:
		s = "Accepted"
	case Failed:
		s = "Failed"
	default:
		return []byte{}, errors.New("unable to marshal unrecognized enum value to JSON")
	}

	return json.Marshal(s)
}

func (v *NotificationResponse) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}

	switch s {
	case "Accepted":
		*v = Accepted
	case "Failed":
		*v = Failed
	default:
		return errors.New("unable to unmarshal unrecognized enum value from JSON")
	}

	return nil
}
