// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

type NotifyOnAssetEndpointProfileUpdateResponsePayload struct {

	// The Command response argument.
	NotificationResponse NotificationResponse `json:"notificationResponse"`
}
