// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

import (
	"encoding/json"
	"errors"
)

type NotificationMessageType int32

const (
	Off NotificationMessageType = iota
	On NotificationMessageType = iota
)

func (v NotificationMessageType) String() string {
	switch v {
	case Off:
		return "Off"
	case On:
		return "On"
	default:
		return ""
	}
}

func (v NotificationMessageType) MarshalJSON() ([]byte, error) {
	var s string
	switch v {
	case Off:
		s = "Off"
	case On:
		s = "On"
	default:
		return []byte{}, errors.New("unable to marshal unrecognized enum value to JSON")
	}

	return json.Marshal(s)
}

func (v *NotificationMessageType) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}

	switch s {
	case "Off":
		*v = Off
	case "On":
		*v = On
	default:
		return errors.New("unable to unmarshal unrecognized enum value from JSON")
	}

	return nil
}
