// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

import (
	"context"

	"github.com/Azure/iot-operations-sdks/go/protocol"
)

type NotifyOnAssetUpdateCommandInvoker struct {
	*protocol.CommandInvoker[NotifyOnAssetUpdateRequestPayload, NotifyOnAssetUpdateResponsePayload]
}

func NewNotifyOnAssetUpdateCommandInvoker(
	app *protocol.Application,
	client protocol.MqttClient,
	requestTopic string,
	opt ...protocol.CommandInvokerOption,
) (*NotifyOnAssetUpdateCommandInvoker, error) {
	var err error
	invoker := &NotifyOnAssetUpdateCommandInvoker{}

	var opts protocol.CommandInvokerOptions
	opts.Apply(
		opt,
		protocol.WithTopicTokens{
			"commandName": "notifyOnAssetUpdate",
		},
	)

	invoker.CommandInvoker, err = protocol.NewCommandInvoker(
		app,
		client,
		protocol.JSON[NotifyOnAssetUpdateRequestPayload]{},
		protocol.JSON[NotifyOnAssetUpdateResponsePayload]{},
		requestTopic,
		&opts,
	)

	return invoker, err
}

func (invoker NotifyOnAssetUpdateCommandInvoker) NotifyOnAssetUpdate(
	ctx context.Context,
	request NotifyOnAssetUpdateRequestPayload,
	opt ...protocol.InvokeOption,
) (*protocol.CommandResponse[NotifyOnAssetUpdateResponsePayload], error) {
	invokerOpts := []protocol.InvokeOption{
		protocol.WithTopicTokenNamespace("ex:"),
	}

	var invokeOpts protocol.InvokeOptions
	invokeOpts.Apply(opt, invokerOpts...)

	response, err := invoker.Invoke(
		ctx,
		request,
		&invokeOpts,
	)

	return response, err
}
