// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

import (
	"encoding/json"
	"errors"
)

type Qos int32

const (
	QosQos0 Qos = iota
	QosQos1 Qos = iota
)

func (v Qos) String() string {
	switch v {
	case QosQos0:
		return "Qos0"
	case QosQos1:
		return "Qos1"
	default:
		return ""
	}
}

func (v Qos) MarshalJSON() ([]byte, error) {
	var s string
	switch v {
	case QosQos0:
		s = "Qos0"
	case QosQos1:
		s = "Qos1"
	default:
		return []byte{}, errors.New("unable to marshal unrecognized enum value to JSON")
	}

	return json.Marshal(s)
}

func (v *Qos) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}

	switch s {
	case "Qos0":
		*v = QosQos0
	case "Qos1":
		*v = QosQos1
	default:
		return errors.New("unable to unmarshal unrecognized enum value from JSON")
	}

	return nil
}
