// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

import (
	"encoding/json"
	"errors"
)

type Retain int32

const (
	RetainKeep Retain = iota
	RetainNever Retain = iota
)

func (v Retain) String() string {
	switch v {
	case RetainKeep:
		return "Keep"
	case RetainNever:
		return "Never"
	default:
		return ""
	}
}

func (v Retain) MarshalJSON() ([]byte, error) {
	var s string
	switch v {
	case RetainKeep:
		s = "Keep"
	case RetainNever:
		s = "Never"
	default:
		return []byte{}, errors.New("unable to marshal unrecognized enum value to JSON")
	}

	return json.Marshal(s)
}

func (v *Retain) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}

	switch s {
	case "Keep":
		*v = RetainKeep
	case "Never":
		*v = RetainNever
	default:
		return errors.New("unable to unmarshal unrecognized enum value from JSON")
	}

	return nil
}
