// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

import (
	"encoding/json"
	"errors"
)

type RetainSchema int32

const (
	Keep RetainSchema = iota
	Never RetainSchema = iota
)

func (v RetainSchema) String() string {
	switch v {
	case Keep:
		return "Keep"
	case Never:
		return "Never"
	default:
		return ""
	}
}

func (v RetainSchema) MarshalJSON() ([]byte, error) {
	var s string
	switch v {
	case Keep:
		s = "Keep"
	case Never:
		s = "Never"
	default:
		return []byte{}, errors.New("unable to marshal unrecognized enum value to JSON")
	}

	return json.Marshal(s)
}

func (v *RetainSchema) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}

	switch s {
	case "Keep":
		*v = Keep
	case "Never":
		*v = Never
	default:
		return errors.New("unable to unmarshal unrecognized enum value from JSON")
	}

	return nil
}
