// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

import (
	"context"

	"github.com/Azure/iot-operations-sdks/go/protocol"
)

type SetNotificationPreferenceForAssetUpdatesCommandInvoker struct {
	*protocol.CommandInvoker[SetNotificationPreferenceForAssetUpdatesRequestPayload, SetNotificationPreferenceForAssetUpdatesResponsePayload]
}

func NewSetNotificationPreferenceForAssetUpdatesCommandInvoker(
	app *protocol.Application,
	client protocol.MqttClient,
	requestTopic string,
	opt ...protocol.CommandInvokerOption,
) (*SetNotificationPreferenceForAssetUpdatesCommandInvoker, error) {
	var err error
	invoker := &SetNotificationPreferenceForAssetUpdatesCommandInvoker{}

	var opts protocol.CommandInvokerOptions
	opts.Apply(
		opt,
		protocol.WithTopicTokens{
			"commandName": "setNotificationPreferenceForAssetUpdates",
		},
	)

	invoker.CommandInvoker, err = protocol.NewCommandInvoker(
		app,
		client,
		protocol.JSON[SetNotificationPreferenceForAssetUpdatesRequestPayload]{},
		protocol.JSON[SetNotificationPreferenceForAssetUpdatesResponsePayload]{},
		requestTopic,
		&opts,
	)

	return invoker, err
}

func (invoker SetNotificationPreferenceForAssetUpdatesCommandInvoker) SetNotificationPreferenceForAssetUpdates(
	ctx context.Context,
	request SetNotificationPreferenceForAssetUpdatesRequestPayload,
	opt ...protocol.InvokeOption,
) (*protocol.CommandResponse[SetNotificationPreferenceForAssetUpdatesResponsePayload], error) {
	invokerOpts := []protocol.InvokeOption{
		protocol.WithTopicTokenNamespace("ex:"),
	}

	var invokeOpts protocol.InvokeOptions
	invokeOpts.Apply(opt, invokerOpts...)

	response, err := invoker.Invoke(
		ctx,
		request,
		&invokeOpts,
	)

	return response, err
}
