// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

type SetNotificationPreferenceForAssetUpdatesRequestSchema struct {

	// The 'assetName' Field.
	AssetName string `json:"assetName"`

	// The 'notificationPreference' Field.
	NotificationPreference NotificationPreference `json:"notificationPreference"`
}
