// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

type Topic struct {

	// The 'path' Field.
	Path string `json:"path"`

	// The 'retain' Field.
	Retain *Retain `json:"retain,omitempty"`
}
