// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

type TrustSettingsSchema struct {

	// The 'issuerList' Field.
	IssuerList *string `json:"issuerList,omitempty"`

	// The 'trustList' Field.
	TrustList *string `json:"trustList,omitempty"`
}
