// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

import (
	"context"

	"github.com/Azure/iot-operations-sdks/go/protocol"
)

type UpdateDeviceStatusCommandInvoker struct {
	*protocol.CommandInvoker[UpdateDeviceStatusRequestPayload, UpdateDeviceStatusResponsePayload]
}

func NewUpdateDeviceStatusCommandInvoker(
	app *protocol.Application,
	client protocol.MqttClient,
	requestTopic string,
	opt ...protocol.CommandInvokerOption,
) (*UpdateDeviceStatusCommandInvoker, error) {
	var err error
	invoker := &UpdateDeviceStatusCommandInvoker{}

	var opts protocol.CommandInvokerOptions
	opts.Apply(
		opt,
		protocol.WithTopicTokens{
			"commandName": "updateDeviceStatus",
		},
	)

	invoker.CommandInvoker, err = protocol.NewCommandInvoker(
		app,
		client,
		protocol.JSON[UpdateDeviceStatusRequestPayload]{},
		protocol.JSON[UpdateDeviceStatusResponsePayload]{},
		requestTopic,
		&opts,
	)

	return invoker, err
}

func (invoker UpdateDeviceStatusCommandInvoker) UpdateDeviceStatus(
	ctx context.Context,
	request UpdateDeviceStatusRequestPayload,
	opt ...protocol.InvokeOption,
) (*protocol.CommandResponse[UpdateDeviceStatusResponsePayload], error) {
	invokerOpts := []protocol.InvokeOption{
		protocol.WithTopicTokenNamespace("ex:"),
	}

	var invokeOpts protocol.InvokeOptions
	invokeOpts.Apply(opt, invokerOpts...)

	response, err := invoker.Invoke(
		ctx,
		request,
		&invokeOpts,
	)

	return response, err
}
