// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

type UpdateDeviceStatusResponsePayload struct {

	// The Command response argument.
	UpdatedDevice Device `json:"updatedDevice"`
}
