// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

type UpdateDeviceStatusRequestPayload struct {

	// The Command request argument.
	DeviceStatusUpdate DeviceStatus `json:"deviceStatusUpdate"`
}
