// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

type UpdateAssetStatusResponsePayload struct {

	// The Command response argument.
	UpdatedAsset Asset `json:"updatedAsset"`
}
