// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package adrbaseservice

import (
	"context"

	"github.com/Azure/iot-operations-sdks/go/protocol"
)

type UpdateAssetEndpointProfileStatusCommandInvoker struct {
	*protocol.CommandInvoker[UpdateAssetEndpointProfileStatusRequestPayload, UpdateAssetEndpointProfileStatusResponsePayload]
}

func NewUpdateAssetEndpointProfileStatusCommandInvoker(
	app *protocol.Application,
	client protocol.MqttClient,
	requestTopic string,
	opt ...protocol.CommandInvokerOption,
) (*UpdateAssetEndpointProfileStatusCommandInvoker, error) {
	var err error
	invoker := &UpdateAssetEndpointProfileStatusCommandInvoker{}

	var opts protocol.CommandInvokerOptions
	opts.Apply(
		opt,
		protocol.WithTopicTokens{
			"commandName": "updateAssetEndpointProfileStatus",
		},
	)

	invoker.CommandInvoker, err = protocol.NewCommandInvoker(
		app,
		client,
		protocol.JSON[UpdateAssetEndpointProfileStatusRequestPayload]{},
		protocol.JSON[UpdateAssetEndpointProfileStatusResponsePayload]{},
		requestTopic,
		&opts,
	)

	return invoker, err
}

func (invoker UpdateAssetEndpointProfileStatusCommandInvoker) UpdateAssetEndpointProfileStatus(
	ctx context.Context,
	request UpdateAssetEndpointProfileStatusRequestPayload,
	opt ...protocol.InvokeOption,
) (*protocol.CommandResponse[UpdateAssetEndpointProfileStatusResponsePayload], error) {
	invokerOpts := []protocol.InvokeOption{
		protocol.WithTopicTokenNamespace("ex:"),
	}

	var invokeOpts protocol.InvokeOptions
	invokeOpts.Apply(opt, invokerOpts...)

	response, err := invoker.Invoke(
		ctx,
		request,
		&invokeOpts,
	)

	return response, err
}
