// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package aeptypeservice

type CreateDiscoveredAssetEndpointProfileResponsePayload struct {

	// The Command response argument.
	CreateDiscoveredAssetEndpointProfileResponse CreateDiscoveredAssetEndpointProfileResponseSchema `json:"createDiscoveredAssetEndpointProfileResponse"`
}
