// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package aeptypeservice

type CreateDiscoveredAssetEndpointProfileResponseSchema struct {

	// status of discovered asset endpoint profile creation
	Status DiscoveredAssetEndpointProfileResponseStatusSchema `json:"status"`
}
