// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package aeptypeservice

import (
	"context"

	"github.com/Azure/iot-operations-sdks/go/protocol"
)

type CreateDiscoveredAssetEndpointProfileCommandInvoker struct {
	*protocol.CommandInvoker[CreateDiscoveredAssetEndpointProfileRequestPayload, CreateDiscoveredAssetEndpointProfileResponsePayload]
}

func NewCreateDiscoveredAssetEndpointProfileCommandInvoker(
	app *protocol.Application,
	client protocol.MqttClient,
	requestTopic string,
	opt ...protocol.CommandInvokerOption,
) (*CreateDiscoveredAssetEndpointProfileCommandInvoker, error) {
	var err error
	invoker := &CreateDiscoveredAssetEndpointProfileCommandInvoker{}

	var opts protocol.CommandInvokerOptions
	opts.Apply(
		opt,
		protocol.WithTopicTokens{
			"commandName": "createDiscoveredAssetEndpointProfile",
		},
	)

	invoker.CommandInvoker, err = protocol.NewCommandInvoker(
		app,
		client,
		protocol.JSON[CreateDiscoveredAssetEndpointProfileRequestPayload]{},
		protocol.JSON[CreateDiscoveredAssetEndpointProfileResponsePayload]{},
		requestTopic,
		&opts,
	)

	return invoker, err
}

func (invoker CreateDiscoveredAssetEndpointProfileCommandInvoker) CreateDiscoveredAssetEndpointProfile(
	ctx context.Context,
	request CreateDiscoveredAssetEndpointProfileRequestPayload,
	opt ...protocol.InvokeOption,
) (*protocol.CommandResponse[CreateDiscoveredAssetEndpointProfileResponsePayload], error) {
	invokerOpts := []protocol.InvokeOption{
		protocol.WithTopicTokenNamespace("ex:"),
	}

	var invokeOpts protocol.InvokeOptions
	invokeOpts.Apply(opt, invokerOpts...)

	response, err := invoker.Invoke(
		ctx,
		request,
		&invokeOpts,
	)

	return response, err
}
