// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package aeptypeservice

type CreateDiscoveredAssetEndpointProfileRequestPayload struct {

	// The Command request argument.
	DiscoveredAssetEndpointProfile DiscoveredAssetEndpointProfile `json:"discoveredAssetEndpointProfile"`
}
