// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package aeptypeservice

import (
	"encoding/json"
	"errors"
)

type DiscoveredAssetEndpointProfileResponseStatusSchema int32

const (
	Created DiscoveredAssetEndpointProfileResponseStatusSchema = iota
	Duplicate DiscoveredAssetEndpointProfileResponseStatusSchema = iota
	Failed DiscoveredAssetEndpointProfileResponseStatusSchema = iota
)

func (v DiscoveredAssetEndpointProfileResponseStatusSchema) String() string {
	switch v {
	case Created:
		return "Created"
	case Duplicate:
		return "Duplicate"
	case Failed:
		return "Failed"
	default:
		return ""
	}
}

func (v DiscoveredAssetEndpointProfileResponseStatusSchema) MarshalJSON() ([]byte, error) {
	var s string
	switch v {
	case Created:
		s = "created"
	case Duplicate:
		s = "duplicate"
	case Failed:
		s = "failed"
	default:
		return []byte{}, errors.New("unable to marshal unrecognized enum value to JSON")
	}

	return json.Marshal(s)
}

func (v *DiscoveredAssetEndpointProfileResponseStatusSchema) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}

	switch s {
	case "created":
		*v = Created
	case "duplicate":
		*v = Duplicate
	case "failed":
		*v = Failed
	default:
		return errors.New("unable to unmarshal unrecognized enum value from JSON")
	}

	return nil
}
