/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.Iot.Operations.Services.AssetAndDeviceRegistry.DeviceDiscoveryService
{
    using System;
    using Azure.Iot.Operations.Services.AssetAndDeviceRegistry;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class AkriServiceErrorException : Exception
    {
        public AkriServiceErrorException(AkriServiceError akriServiceError)
            : base(akriServiceError.Message)
        {
            AkriServiceError = akriServiceError;
        }

        public AkriServiceError AkriServiceError { get; }
    }
}
