/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.Iot.Operations.Services.AssetAndDeviceRegistry.DeviceDiscoveryService
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using Azure.Iot.Operations.Services.AssetAndDeviceRegistry;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompilerLib", "0.10.0.0")]
    public partial class CreateOrUpdateDiscoveredDeviceResponseSchema
    {
        /// <summary>
        /// Error details, if the discovered device creation or update failed.
        /// </summary>
        [JsonPropertyName("createOrUpdateDiscoveredDeviceError")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public AkriServiceError? CreateOrUpdateDiscoveredDeviceError { get; set; } = default;

        /// <summary>
        /// The discovered device response.
        /// </summary>
        [JsonPropertyName("discoveredDeviceResponse")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public DiscoveredDeviceResponseSchema? DiscoveredDeviceResponse { get; set; } = default;

    }
}
