/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

use std::error::Error;
use std::fmt;

use super::schema_registry_error::SchemaRegistryError;

impl fmt::Display for SchemaRegistryError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.message)
    }
}

impl Error for SchemaRegistryError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        None
    }
}
