/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v0.10.0.0; DO NOT EDIT. */

use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone)]
pub enum SchemaRegistryErrorTarget {
    #[serde(rename = "Description")]
    DescriptionProperty,
    #[serde(rename = "DisplayName")]
    DisplayNameProperty,
    #[serde(rename = "Format")]
    FormatProperty,
    #[serde(rename = "Name")]
    NameProperty,
    #[serde(rename = "SchemaArmResource")]
    SchemaArmResource,
    #[serde(rename = "SchemaContent")]
    SchemaContentProperty,
    #[serde(rename = "SchemaRegistryResource")]
    SchemaRegistryArmResource,
    #[serde(rename = "SchemaType")]
    SchemaTypeProperty,
    #[serde(rename = "SchemaVersionArmResource")]
    SchemaVersionArmResource,
    #[serde(rename = "Tags")]
    TagsProperty,
    #[serde(rename = "Version")]
    VersionProperty,
}
