/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

use serde::{Deserialize, Serialize};

/// Metric type: Counter, Gauge, Histogram
#[derive(Serialize, Deserialize, Debug, Clone)]
pub enum AkriMetricType {
    #[serde(rename = "Counter")]
    Counter,
    #[serde(rename = "Gauge")]
    Gauge,
    #[serde(rename = "Histogram")]
    Histogram,
}
