/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */
#![allow(unused_imports)]

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use derive_builder::Builder;
use iso8601_duration::Duration;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::akri_metric_type::AkriMetricType;
use super::akri_metric_operation::AkriMetricOperation;
use super::super::common_types::{b64::Bytes, date_only::Date, decimal::Decimal, time_only::Time};

/// Metric data
#[derive(Serialize, Deserialize, Debug, Clone, Builder)]
pub struct AkriMetric {
    /// Custom labels to associate with the metric
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub labels: Option<HashMap<String, String>>,

    /// Metric type: Counter, Gauge, Histogram
    #[serde(rename = "metricType")]
    pub metric_type: AkriMetricType,

    /// Name of the metric
    pub name: String,

    /// Operation name: Create, Increment, Record
    pub operation: AkriMetricOperation,

    /// Timestamp of when the metric was recorded
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub timestamp: Option<DateTime<Utc>>,

    /// Unit of the metric
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub unit: Option<String>,

    /// Value of the metric
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub value: Option<f64>,
}
