/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

use serde::{Deserialize, Serialize};

/// Operation name: Create metric, Increment counter, Record gauge/histogram
#[derive(Serialize, Deserialize, Debug, Clone)]
pub enum AkriMetricOperation {
    #[serde(rename = "create")]
    Create,
    #[serde(rename = "increment")]
    Increment,
    #[serde(rename = "record")]
    Record,
}
