/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

use std::collections::HashMap;

use azure_iot_operations_mqtt::interface::ManagedClient;
use azure_iot_operations_protocol::common::aio_protocol_error::AIOProtocolError;
use azure_iot_operations_protocol::common::payload_serialize::PayloadSerialize;
use azure_iot_operations_protocol::rpc_command;
use azure_iot_operations_protocol::application::ApplicationContext;

use super::publish_metrics_request_payload::PublishMetricsRequestPayload;
use super::publish_metrics_response_payload::PublishMetricsResponsePayload;
use super::MODEL_ID;
use super::REQUEST_TOPIC_PATTERN;
use super::super::common_types::common_options::CommandOptions;

pub type PublishMetricsRequest =
    rpc_command::executor::Request<PublishMetricsRequestPayload, PublishMetricsResponsePayload>;
pub type PublishMetricsResponse = rpc_command::executor::Response<PublishMetricsResponsePayload>;
pub type PublishMetricsResponseBuilderError = rpc_command::executor::ResponseBuilderError;

/// Builder for [`PublishMetricsResponse`]
#[derive(Default)]
pub struct PublishMetricsResponseBuilder {
    inner_builder: rpc_command::executor::ResponseBuilder<PublishMetricsResponsePayload>,
}

impl PublishMetricsResponseBuilder {
    /// Custom user data to set on the response
    pub fn custom_user_data(&mut self, custom_user_data: Vec<(String, String)>) -> &mut Self {
        self.inner_builder.custom_user_data(custom_user_data);
        self
    }

    /// Payload of the response
    ///
    /// # Errors
    /// If the payload cannot be serialized
    pub fn payload(
        &mut self,
        payload: PublishMetricsResponsePayload,
    ) -> Result<&mut Self, AIOProtocolError> {
        self.inner_builder.payload(payload)?;
        Ok(self)
    }

    /// Builds a new `PublishMetricsResponse`
    ///
    /// # Errors
    /// If a required field has not been initialized
    #[allow(clippy::missing_panics_doc)]    // The panic is not possible
    pub fn build(&mut self) -> Result<PublishMetricsResponse, PublishMetricsResponseBuilderError> {
        self.inner_builder.build()
    }
}

/// Command Executor for `publishMetrics`
pub struct PublishMetricsCommandExecutor<C>(
    rpc_command::Executor<PublishMetricsRequestPayload, PublishMetricsResponsePayload, C>,
)
where
    C: ManagedClient + Clone + Send + Sync + 'static,
    C::PubReceiver: Send + Sync + 'static;

impl<C> PublishMetricsCommandExecutor<C>
where
    C: ManagedClient + Clone + Send + Sync + 'static,
    C::PubReceiver: Send + Sync + 'static,
{
    /// Creates a new [`PublishMetricsCommandExecutor`]
    ///
    /// # Panics
    /// If the DTDL that generated this code was invalid
    pub fn new(application_context: ApplicationContext, client: C, options: &CommandOptions) -> Self {
        let mut executor_options_builder = rpc_command::executor::OptionsBuilder::default();
        if let Some(topic_namespace) = &options.topic_namespace {
            executor_options_builder.topic_namespace(topic_namespace.clone());
        }

        let mut topic_token_map: HashMap<String, String> = options
            .topic_token_map
            .clone()
            .into_iter()
            .map(|(k, v)| (format!("ex:{k}"), v))
            .collect();

        topic_token_map.insert("modelId".to_string(), MODEL_ID.to_string());
        topic_token_map.insert("executorId".to_string(), client.client_id().to_string());
        topic_token_map.insert("commandName".to_string(), "publishMetrics".to_string());

        let executor_options = executor_options_builder
            .request_topic_pattern(REQUEST_TOPIC_PATTERN)
            .command_name("publishMetrics")
            .is_idempotent(false)
            .topic_token_map(topic_token_map)
            .build()
            .expect("DTDL schema generated invalid arguments");

        Self(
            rpc_command::Executor::new(application_context, client, executor_options)
                .expect("DTDL schema generated invalid arguments"),
        )
    }

    /// Receive the next [`PublishMetricsRequest`] or [`None`] if there will be no more requests
    ///
    /// # Errors
    /// [`AIOProtocolError`] if there is a failure receiving a request
    pub async fn recv(&mut self) -> Option<Result<PublishMetricsRequest, AIOProtocolError>> {
        self.0.recv().await
    }

    /// Shutdown the [`PublishMetricsCommandExecutor`]. Unsubscribes from the request topic.
    ///
    /// Returns Ok(()) on success, otherwise returns [`AIOProtocolError`].
    /// # Errors
    /// [`AIOProtocolError`] of kind [`ClientError`](azure_iot_operations_protocol::common::aio_protocol_error::AIOProtocolErrorKind::ClientError) if the unsubscribe fails or if the unsuback reason code doesn't indicate success.
    pub async fn shutdown(&mut self) -> Result<(), AIOProtocolError> {
        self.0.shutdown().await
    }
}
