// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package schemaregistry

type PutRequestSchema struct {

	// Human-readable description of the schema.
	Description *string `json:"description,omitempty"`

	// Human-readable display name.
	DisplayName *string `json:"displayName,omitempty"`

	// Format of the schema.
	Format Format `json:"format"`

	// Content stored in the schema.
	SchemaContent string `json:"schemaContent"`

	// Type of the schema.
	SchemaType SchemaType `json:"schemaType"`

	// Schema tags.
	Tags map[string]string `json:"tags,omitempty"`

	// Version of the schema. Allowed between 0-9.
	Version string `json:"version"`
}
