// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v0.10.0.0; DO NOT EDIT. */

using System;

namespace Azure.Iot.Operations.Services.AssetAndDeviceRegistry
{
    [AttributeUsage(AttributeTargets.Class)]
    public class PropertyTopicAttribute(string topic) : Attribute
    {
        public string Topic { get; set; } = topic;
    }
}
