namespace Azure.Iot.Operations.ProtocolCompilerLib
{
    public enum SchemaKind
    {
        Array,
        Boolean,
        Bytes,
        Byte,
        DateTime,
        Date,
        Decimal,
        Double,
        Duration,
        EnumInt,
        EnumString,
        Float,
        Integer,
        Long,
        Map,
        Object,
        Reference,
        Schema,
        Short,
        String,
        Time,
        UnsignedByte,
        UnsignedInteger,
        UnsignedLong,
        UnsignedShort,
        Uuid,
    }
}
