/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone)]
pub enum CodeSchema {
    #[serde(rename = "BadRequest")]
    BadRequest,
    #[serde(rename = "InternalError")]
    InternalError,
    #[serde(rename = "KubeError")]
    KubeError,
    #[serde(rename = "SerializationError")]
    SerializationError,
}
