/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */
#![allow(unused_imports)]

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use derive_builder::Builder;
use iso8601_duration::Duration;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::super::common_types::{b64::Bytes, date_only::Date, decimal::Decimal, time_only::Time};
use super::discovered_device_inbound_endpoint_schema::DiscoveredDeviceInboundEndpointSchema;
use super::discovered_device_outbound_endpoints_schema::DiscoveredDeviceOutboundEndpointsSchema;

#[derive(Serialize, Deserialize, Debug, Clone, Builder)]
pub struct DiscoveredDeviceEndpoints {
    /// Set of endpoints to connect to the device.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub inbound: Option<HashMap<String, DiscoveredDeviceInboundEndpointSchema>>,

    /// Property bag contains the device's outbound endpoints
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub outbound: Option<DiscoveredDeviceOutboundEndpointsSchema>,
}
