/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */
#![allow(unused_imports)]

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use derive_builder::Builder;
use iso8601_duration::Duration;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::super::common_types::{b64::Bytes, date_only::Date, decimal::Decimal, time_only::Time};
use super::asset_management_group_action_status_schema_element_schema::AssetManagementGroupActionStatusSchemaElementSchema;

#[derive(Serialize, Deserialize, Debug, Clone, Builder)]
pub struct AssetManagementGroupStatusSchemaElementSchema {
    /// Array of action statuses that describe the status of each action.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub actions: Option<Vec<AssetManagementGroupActionStatusSchemaElementSchema>>,

    /// The name of the managementgroup. Must be unique within the status.managementGroup array. This name is used to correlate between the spec and status management group information.
    pub name: String,
}
