/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */
#![allow(unused_imports)]

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use derive_builder::Builder;
use iso8601_duration::Duration;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::super::common_types::{b64::Bytes, date_only::Date, decimal::Decimal, time_only::Time};
use super::asset_management_group_action_schema_element_schema::AssetManagementGroupActionSchemaElementSchema;

#[derive(Serialize, Deserialize, Debug, Clone, Builder)]
pub struct AssetManagementGroupSchemaElementSchema {
    /// Actions for this management group.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub actions: Option<Vec<AssetManagementGroupActionSchemaElementSchema>>,

    /// Default time out in seconds for the management group.
    #[serde(rename = "defaultTimeOutInSeconds")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub default_time_out_in_seconds: Option<u32>,

    /// The default MQTT topic for the management group.
    #[serde(rename = "defaultTopic")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub default_topic: Option<String>,

    /// Configuration for the mangement group.
    #[serde(rename = "managementGroupConfiguration")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub management_group_configuration: Option<String>,

    /// Name of the management group.
    pub name: String,

    /// URI or type definition id in companion spec.
    #[serde(rename = "typeRef")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub type_ref: Option<String>,
}
