/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v0.10.0.0; DO NOT EDIT. */
#![allow(unused_imports)]

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use derive_builder::Builder;
use iso8601_duration::Duration;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::super::common_types::{b64::Bytes, date_only::Date, decimal::Decimal, time_only::Time};
use super::asset_dataset_event_stream_status::AssetDatasetEventStreamStatus;

#[derive(Serialize, Deserialize, Debug, Clone, Builder)]
pub struct AssetEventGroupStatusSchemaElementSchema {
    /// Array of event statuses that describe the status of each event in the event group.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub events: Option<Vec<AssetDatasetEventStreamStatus>>,

    /// The name of the event group. Must be unique within the status.eventGroups array. This name is used to correlate between the spec and status event group information.
    pub name: String,
}
