/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */
#![allow(unused_imports)]

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use derive_builder::Builder;
use iso8601_duration::Duration;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::super::common_types::{b64::Bytes, date_only::Date, decimal::Decimal, time_only::Time};
use super::asset_management_group_action_type::AssetManagementGroupActionType;

#[derive(Serialize, Deserialize, Debug, Clone, Builder)]
pub struct AssetManagementGroupActionSchemaElementSchema {
    /// Configuration for the action.
    #[serde(rename = "actionConfiguration")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub action_configuration: Option<String>,

    /// Type of the action.
    #[serde(rename = "actionType")]
    pub action_type: AssetManagementGroupActionType,

    /// Name of the action.
    pub name: String,

    /// TargetUri of action.
    #[serde(rename = "targetUri")]
    pub target_uri: String,

    /// Time out in seconds for the action
    #[serde(rename = "timeOutInSeconds")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub time_out_in_seconds: Option<u32>,

    /// The MQTT topic.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub topic: Option<String>,

    /// URI or type definition id in companion spec.
    #[serde(rename = "typeRef")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub type_ref: Option<String>,
}
