/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */
#![allow(unused_imports)]

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use derive_builder::Builder;
use iso8601_duration::Duration;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::super::common_types::{b64::Bytes, date_only::Date, decimal::Decimal, time_only::Time};
use super::inbound_schema_map_value_schema::InboundSchemaMapValueSchema;
use super::outbound_schema::OutboundSchema;

#[derive(Serialize, Deserialize, Debug, Clone, Builder)]
pub struct DeviceEndpointsSchema {
    /// The 'inbound' Field.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub inbound: Option<HashMap<String, InboundSchemaMapValueSchema>>,

    /// Set of endpoints for device to connect to.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub outbound: Option<OutboundSchema>,
}
