/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */
#![allow(unused_imports)]

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use derive_builder::Builder;
use iso8601_duration::Duration;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::super::common_types::{b64::Bytes, date_only::Date, decimal::Decimal, time_only::Time};
use super::device_endpoints_schema::DeviceEndpointsSchema;

#[derive(Serialize, Deserialize, Debug, Clone, Builder)]
pub struct DeviceSpecificationSchema {
    /// The 'attributes' Field.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub attributes: Option<HashMap<String, String>>,

    /// The 'discoveredDeviceRef' Field.
    #[serde(rename = "discoveredDeviceRef")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub discovered_device_ref: Option<String>,

    /// The 'enabled' Field.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub enabled: Option<bool>,

    /// The 'endpoints' Field.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub endpoints: Option<DeviceEndpointsSchema>,

    /// The 'externalDeviceId' Field.
    #[serde(rename = "externalDeviceId")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub external_device_id: Option<String>,

    /// The 'lastTransitionTime' Field.
    #[serde(rename = "lastTransitionTime")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub last_transition_time: Option<DateTime<Utc>>,

    /// The 'manufacturer' Field.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub manufacturer: Option<String>,

    /// The 'model' Field.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub model: Option<String>,

    /// The 'operatingSystem' Field.
    #[serde(rename = "operatingSystem")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub operating_system: Option<String>,

    /// The 'operatingSystemVersion' Field.
    #[serde(rename = "operatingSystemVersion")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub operating_system_version: Option<String>,

    /// The 'uuid' Field.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub uuid: Option<String>,

    /// The 'version' Field.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub version: Option<u64>,
}
