/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */
#![allow(unused_imports)]

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use derive_builder::Builder;
use iso8601_duration::Duration;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::super::common_types::{b64::Bytes, date_only::Date, decimal::Decimal, time_only::Time};
use super::discovered_asset_management_group_action::DiscoveredAssetManagementGroupAction;

#[derive(Serialize, Deserialize, Debug, Clone, Builder)]
pub struct DiscoveredAssetManagementGroup {
    /// The 'actions' Field.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub actions: Option<Vec<DiscoveredAssetManagementGroupAction>>,

    /// The 'defaultTimeOutInSeconds' Field.
    #[serde(rename = "defaultTimeOutInSeconds")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub default_time_out_in_seconds: Option<u32>,

    /// The 'defaultTopic' Field.
    #[serde(rename = "defaultTopic")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub default_topic: Option<String>,

    /// The 'lastUpdatedOn' Field.
    #[serde(rename = "lastUpdatedOn")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub last_updated_on: Option<DateTime<Utc>>,

    /// The 'managementGroupConfiguration' Field.
    #[serde(rename = "managementGroupConfiguration")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub management_group_configuration: Option<String>,

    /// The 'name' Field.
    pub name: String,

    /// The 'typeRef' Field.
    #[serde(rename = "typeRef")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub type_ref: Option<String>,
}
