/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v0.10.0.0; DO NOT EDIT. */
#![allow(unused_imports)]

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use derive_builder::Builder;
use iso8601_duration::Duration;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::super::common_types::{b64::Bytes, date_only::Date, decimal::Decimal, time_only::Time};
use super::destination_configuration::DestinationConfiguration;
use super::event_stream_target::EventStreamTarget;

#[derive(Serialize, Deserialize, Debug, Clone, Builder)]
pub struct EventStreamDestination {
    /// The destination configuration.
    pub configuration: DestinationConfiguration,

    /// The target destination.
    pub target: EventStreamTarget,
}
