/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v0.10.0.0; DO NOT EDIT. */
#![allow(unused_imports)]

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use derive_builder::Builder;
use iso8601_duration::Duration;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::super::common_types::{b64::Bytes, date_only::Date, decimal::Decimal, time_only::Time};
use super::akri_service_error::AkriServiceError;
use super::asset::Asset;

#[derive(Serialize, Deserialize, Debug, Clone, Builder)]
pub struct GetAssetResponseSchema {
    /// The asset resource
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub asset: Option<Asset>,

    /// Error details, if the asset could not be retrieved.
    #[serde(rename = "getAssetError")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub get_asset_error: Option<AkriServiceError>,
}
