/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v0.10.0.0; DO NOT EDIT. */
#![allow(unused_imports)]

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use derive_builder::Builder;
use iso8601_duration::Duration;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::super::common_types::{b64::Bytes, date_only::Date, decimal::Decimal, time_only::Time};
use super::notification_preference::NotificationPreference;

#[derive(Serialize, Deserialize, Debug, Clone, Builder)]
pub struct SetNotificationPreferenceForAssetUpdatesRequestSchema {
    /// The name of the asset to set the notification preference for.
    #[serde(rename = "assetName")]
    pub asset_name: String,

    /// The notification preference to set for the asset updates.
    #[serde(rename = "notificationPreference")]
    pub notification_preference: NotificationPreference,
}
