/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v0.10.0.0; DO NOT EDIT. */
#![allow(unused_imports)]

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use derive_builder::Builder;
use iso8601_duration::Duration;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::super::common_types::{b64::Bytes, date_only::Date, decimal::Decimal, time_only::Time};
use super::akri_service_error::AkriServiceError;

#[derive(Serialize, Deserialize, Debug, Clone, Builder)]
pub struct SetNotificationPreferenceForAssetUpdatesResponseSchema {
    /// The response payload indicating that the operation was successful.
    #[serde(rename = "responsePayload")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub response_payload: Option<String>,

    /// Error details, if setting the notification preference for asset updates failed.
    #[serde(rename = "setNotificationPreferenceForAssetUpdatesError")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub set_notification_preference_for_asset_updates_error: Option<AkriServiceError>,
}
