/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */
#![allow(unused_imports)]

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use derive_builder::Builder;
use iso8601_duration::Duration;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::super::common_types::{b64::Bytes, date_only::Date, decimal::Decimal, time_only::Time};

#[derive(Serialize, Deserialize, Debug, Clone, Builder)]
pub struct TrustSettingsSchema {
    /// Secret reference to the issuers list to trust.
    #[serde(rename = "issuerList")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub issuer_list: Option<String>,

    /// Secret reference to certificates list to trust.
    #[serde(rename = "trustList")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub trust_list: Option<String>,
}
