/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */
#![allow(unused_imports)]

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use derive_builder::Builder;
use iso8601_duration::Duration;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::super::common_types::{b64::Bytes, date_only::Date, decimal::Decimal, time_only::Time};
use super::akri_service_error::AkriServiceError;
use super::asset_status::AssetStatus;

#[derive(Serialize, Deserialize, Debug, Clone, Builder)]
pub struct UpdateAssetStatusResponseSchema {
    /// Error details, if the asset status update failed.
    #[serde(rename = "updateAssetStatusError")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub update_asset_status_error: Option<AkriServiceError>,

    /// The updated asset status.
    #[serde(rename = "updatedAssetStatus")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub updated_asset_status: Option<AssetStatus>,
}
