/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.Iot.Operations.Services.AssetAndDeviceRegistry.AdrBaseService
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using Azure.Iot.Operations.Services.AssetAndDeviceRegistry;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class AkriServiceError : IJsonOnDeserialized, IJsonOnSerializing
    {
        /// <summary>
        /// The 'code' Field.
        /// </summary>
        [JsonPropertyName("code")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public string Code { get; set; } = default!;

        /// <summary>
        /// The 'message' Field.
        /// </summary>
        [JsonPropertyName("message")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public string Message { get; set; } = default!;

        /// <summary>
        /// The 'timestamp' Field.
        /// </summary>
        [JsonPropertyName("timestamp")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public DateTime Timestamp { get; set; } = default!;

        void IJsonOnDeserialized.OnDeserialized()
        {
            if (Code is null)
            {
                throw new ArgumentNullException("code field cannot be null");
            }
            if (Message is null)
            {
                throw new ArgumentNullException("message field cannot be null");
            }
        }

        void IJsonOnSerializing.OnSerializing()
        {
            if (Code is null)
            {
                throw new ArgumentNullException("code field cannot be null");
            }
            if (Message is null)
            {
                throw new ArgumentNullException("message field cannot be null");
            }
        }
    }
}
