/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.Iot.Operations.Services.AssetAndDeviceRegistry.AdrBaseService
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using Azure.Iot.Operations.Services.AssetAndDeviceRegistry;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class AssetDeviceRef : IJsonOnDeserialized, IJsonOnSerializing
    {
        /// <summary>
        /// The 'deviceName' Field.
        /// </summary>
        [JsonPropertyName("deviceName")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public string DeviceName { get; set; } = default!;

        /// <summary>
        /// The 'endpointName' Field.
        /// </summary>
        [JsonPropertyName("endpointName")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public string EndpointName { get; set; } = default!;

        void IJsonOnDeserialized.OnDeserialized()
        {
            if (DeviceName is null)
            {
                throw new ArgumentNullException("deviceName field cannot be null");
            }
            if (EndpointName is null)
            {
                throw new ArgumentNullException("endpointName field cannot be null");
            }
        }

        void IJsonOnSerializing.OnSerializing()
        {
            if (DeviceName is null)
            {
                throw new ArgumentNullException("deviceName field cannot be null");
            }
            if (EndpointName is null)
            {
                throw new ArgumentNullException("endpointName field cannot be null");
            }
        }
    }
}
