/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.Iot.Operations.Services.AssetAndDeviceRegistry.AdrBaseService
{
    using System;
    using System.Collections.Generic;
    using Azure.Iot.Operations.Protocol;
    using Azure.Iot.Operations.Protocol.Telemetry;
    using Azure.Iot.Operations.Protocol.Models;
    using Azure.Iot.Operations.Services.AssetAndDeviceRegistry;

    public static partial class AdrBaseService
    {
        /// <summary>
        /// Specializes the <c>TelemetryReceiver</c> class for type <c>AssetEndpointProfileUpdateEventTelemetry</c>.
        /// </summary>
        public class AssetEndpointProfileUpdateEventTelemetryReceiver : TelemetryReceiver<AssetEndpointProfileUpdateEventTelemetry>
        {
            /// <summary>
            /// Initializes a new instance of the <see cref="AssetEndpointProfileUpdateEventTelemetryReceiver"/> class.
            /// </summary>
            public AssetEndpointProfileUpdateEventTelemetryReceiver(ApplicationContext applicationContext, IMqttPubSubClient mqttClient)
                : base(applicationContext, mqttClient, new Utf8JsonSerializer())
            {
                TopicTokenMap["modelId"] = "dtmi:com:microsoft:akri:AdrBaseService;1";
                TopicTokenMap["telemetryName"] = "assetEndpointProfileUpdateEvent";
            }
        }
    }
}
