/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.Iot.Operations.Services.AssetAndDeviceRegistry.AdrBaseService
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using Azure.Iot.Operations.Services.AssetAndDeviceRegistry;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompilerLib", "0.10.0.0")]
    public partial class AssetUpdateEventSchema : IJsonOnDeserialized, IJsonOnSerializing
    {
        /// <summary>
        /// The updated asset resource.
        /// </summary>
        [JsonPropertyName("asset")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public Asset Asset { get; set; } = default!;

        /// <summary>
        /// The name of the asset that was updated.
        /// </summary>
        [JsonPropertyName("assetName")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public string AssetName { get; set; } = default!;

        void IJsonOnDeserialized.OnDeserialized()
        {
            if (Asset is null)
            {
                throw new ArgumentNullException("asset field cannot be null");
            }
            if (AssetName is null)
            {
                throw new ArgumentNullException("assetName field cannot be null");
            }
        }

        void IJsonOnSerializing.OnSerializing()
        {
            if (Asset is null)
            {
                throw new ArgumentNullException("asset field cannot be null");
            }
            if (AssetName is null)
            {
                throw new ArgumentNullException("assetName field cannot be null");
            }
        }
    }
}
