/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.Iot.Operations.Services.AssetAndDeviceRegistry.AdrBaseService
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using Azure.Iot.Operations.Services.AssetAndDeviceRegistry;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class AuthenticationSchema
    {
        /// <summary>
        /// The 'method' Field.
        /// </summary>
        [JsonPropertyName("method")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public MethodSchema Method { get; set; } = default!;

        /// <summary>
        /// The 'usernamePasswordCredentials' Field.
        /// </summary>
        [JsonPropertyName("usernamePasswordCredentials")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public UsernamePasswordCredentialsSchema? UsernamePasswordCredentials { get; set; } = default;

        /// <summary>
        /// The 'x509Credentials' Field.
        /// </summary>
        [JsonPropertyName("x509Credentials")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public X509credentialsSchema? X509credentials { get; set; } = default;

    }
}
