/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.Iot.Operations.Services.AssetAndDeviceRegistry.AdrBaseService
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using Azure.Iot.Operations.Services.AssetAndDeviceRegistry;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompilerLib", "0.10.0.0")]
    public partial class AuthenticationSchema
    {
        /// <summary>
        /// Defines the method to authenticate the user of the client at the server.
        /// </summary>
        [JsonPropertyName("method")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public MethodSchema Method { get; set; } = default!;

        /// <summary>
        /// The credentials for authentication mode UsernamePassword.
        /// </summary>
        [JsonPropertyName("usernamePasswordCredentials")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public UsernamePasswordCredentialsSchema? UsernamePasswordCredentials { get; set; } = default;

        /// <summary>
        /// The x509 certificate for authentication mode Certificate.
        /// </summary>
        [JsonPropertyName("x509Credentials")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public X509credentialsSchema? X509credentials { get; set; } = default;

    }
}
