/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.Iot.Operations.Services.AssetAndDeviceRegistry.AdrBaseService
{
    using System.Runtime.Serialization;
    using System.Text.Json.Serialization;

    [JsonConverter(typeof(JsonStringEnumMemberConverter))]
    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompilerLib", "0.10.0.0")]
    public enum CodeSchema
    {
        [EnumMember(Value = @"BadRequest")]
        BadRequest = 0,
        [EnumMember(Value = @"InternalError")]
        InternalError = 1,
        [EnumMember(Value = @"KubeError")]
        KubeError = 2,
        [EnumMember(Value = @"SerializationError")]
        SerializationError = 3,
        [EnumMember(Value = @"Unauthorized")]
        Unauthorized = 4,
    }
}
