/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.Iot.Operations.Services.AssetAndDeviceRegistry.AdrBaseService
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using Azure.Iot.Operations.Services.AssetAndDeviceRegistry;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class CreateOrUpdateDiscoveredAssetResponseSchema
    {
        /// <summary>
        /// The 'createOrUpdateDiscoveredAssetError' Field.
        /// </summary>
        [JsonPropertyName("createOrUpdateDiscoveredAssetError")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public AkriServiceError? CreateOrUpdateDiscoveredAssetError { get; set; } = default;

        /// <summary>
        /// The 'discoveredAssetResponse' Field.
        /// </summary>
        [JsonPropertyName("discoveredAssetResponse")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public DiscoveredAssetResponseSchema? DiscoveredAssetResponse { get; set; } = default;

    }
}
