/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.Iot.Operations.Services.AssetAndDeviceRegistry.AdrBaseService
{
    using System;
    using System.Collections.Generic;
    using Azure.Iot.Operations.Protocol;
    using Azure.Iot.Operations.Protocol.RPC;
    using Azure.Iot.Operations.Protocol.Models;
    using Azure.Iot.Operations.Services.AssetAndDeviceRegistry;

    public static partial class AdrBaseService
    {
        /// <summary>
        /// Specializes the <c>CommandInvoker</c> class for Command 'createOrUpdateDiscoveredAsset'.
        /// </summary>
        public class CreateOrUpdateDiscoveredAssetCommandInvoker : CommandInvoker<CreateOrUpdateDiscoveredAssetRequestPayload, CreateOrUpdateDiscoveredAssetResponseSchema>
        {
            /// <summary>
            /// Initializes a new instance of the <see cref="CreateOrUpdateDiscoveredAssetCommandInvoker"/> class.
            /// </summary>
            public CreateOrUpdateDiscoveredAssetCommandInvoker(ApplicationContext applicationContext, IMqttPubSubClient mqttClient)
                : base(applicationContext, mqttClient, "createOrUpdateDiscoveredAsset", new Utf8JsonSerializer())
            {
                this.ResponseTopicPrefix = "clients/{invokerClientId}"; // default value, can be overwritten by user code

                TopicTokenMap["modelId"] = "dtmi:com:microsoft:akri:AdrBaseService;1";
                if (mqttClient.ClientId != null)
                {
                    TopicTokenMap["invokerClientId"] = mqttClient.ClientId;
                }
                TopicTokenMap["commandName"] = "createOrUpdateDiscoveredAsset";
            }
        }
    }
}
