/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.Iot.Operations.Services.AssetAndDeviceRegistry.AdrBaseService
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using Azure.Iot.Operations.Services.AssetAndDeviceRegistry;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class DestinationConfiguration
    {
        /// <summary>
        /// The 'key' Field.
        /// </summary>
        [JsonPropertyName("key")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string? Key { get; set; } = default;

        /// <summary>
        /// The 'path' Field.
        /// </summary>
        [JsonPropertyName("path")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string? Path { get; set; } = default;

        /// <summary>
        /// The 'qos' Field.
        /// </summary>
        [JsonPropertyName("qos")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public QoS? Qos { get; set; } = default;

        /// <summary>
        /// The 'retain' Field.
        /// </summary>
        [JsonPropertyName("retain")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public Retain? Retain { get; set; } = default;

        /// <summary>
        /// The 'topic' Field.
        /// </summary>
        [JsonPropertyName("topic")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string? Topic { get; set; } = default;

        /// <summary>
        /// The 'ttl' Field.
        /// </summary>
        [JsonPropertyName("ttl")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public ulong? Ttl { get; set; } = default;

    }
}
