/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.Iot.Operations.Services.AssetAndDeviceRegistry.AdrBaseService
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using Azure.Iot.Operations.Services.AssetAndDeviceRegistry;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompilerLib", "0.10.0.0")]
    public partial class GetAssetStatusResponseSchema
    {
        /// <summary>
        /// The asset status
        /// </summary>
        [JsonPropertyName("assetStatus")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public AssetStatus? AssetStatus { get; set; } = default;

        /// <summary>
        /// Error details, if the asset status could not be retrieved.
        /// </summary>
        [JsonPropertyName("getAssetStatusError")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public AkriServiceError? GetAssetStatusError { get; set; } = default;

    }
}
