/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.Iot.Operations.Services.AssetAndDeviceRegistry.AdrBaseService
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using Azure.Iot.Operations.Services.AssetAndDeviceRegistry;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompilerLib", "0.10.0.0")]
    public partial class GetDeviceStatusResponseSchema
    {
        /// <summary>
        /// The device status, containing the specific inbound endpoint status as specified by the request.
        /// </summary>
        [JsonPropertyName("deviceStatus")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public DeviceStatus? DeviceStatus { get; set; } = default;

        /// <summary>
        /// Error details, if the device status could not be retrieved.
        /// </summary>
        [JsonPropertyName("getDeviceStatusError")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public AkriServiceError? GetDeviceStatusError { get; set; } = default;

    }
}
