/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.Iot.Operations.Services.AssetAndDeviceRegistry.AdrBaseService
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using Azure.Iot.Operations.Services.AssetAndDeviceRegistry;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class GetDeviceStatusResponseSchema
    {
        /// <summary>
        /// The 'deviceStatus' Field.
        /// </summary>
        [JsonPropertyName("deviceStatus")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public DeviceStatus? DeviceStatus { get; set; } = default;

        /// <summary>
        /// The 'getDeviceStatusError' Field.
        /// </summary>
        [JsonPropertyName("getDeviceStatusError")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public AkriServiceError? GetDeviceStatusError { get; set; } = default;

    }
}
