/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.Iot.Operations.Services.AssetAndDeviceRegistry.AdrBaseService
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using Azure.Iot.Operations.Services.AssetAndDeviceRegistry;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class MessageSchemaReference
    {
        /// <summary>
        /// The 'schemaName' Field.
        /// </summary>
        [JsonPropertyName("schemaName")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string? SchemaName { get; set; } = default;

        /// <summary>
        /// The 'schemaNamespace' Field.
        /// </summary>
        [JsonPropertyName("schemaNamespace")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string? SchemaNamespace { get; set; } = default;

        /// <summary>
        /// The 'schemaVersion' Field.
        /// </summary>
        [JsonPropertyName("schemaVersion")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string? SchemaVersion { get; set; } = default;

    }
}
