/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.Iot.Operations.Services.AssetAndDeviceRegistry.AdrBaseService
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml;
    using Azure.Iot.Operations.Protocol;
    using Azure.Iot.Operations.Protocol.RPC;
    using Azure.Iot.Operations.Protocol.Models;
    using Azure.Iot.Operations.Services.AssetAndDeviceRegistry;

    public static partial class AdrBaseService
    {
        /// <summary>
        /// Specializes a <c>CommandExecutor</c> class for Command 'notifyOnAssetUpdate'.
        /// </summary>
        public class NotifyOnAssetUpdateCommandExecutor : CommandExecutor<NotifyOnAssetUpdateRequestPayload, NotifyOnAssetUpdateResponsePayload>
        {
            /// <summary>
            /// Initializes a new instance of the <see cref="NotifyOnAssetUpdateCommandExecutor"/> class.
            /// </summary>
            public NotifyOnAssetUpdateCommandExecutor(ApplicationContext applicationContext, IMqttPubSubClient mqttClient)
                : base(applicationContext, mqttClient, "notifyOnAssetUpdate", new Utf8JsonSerializer())
            {
                TopicTokenMap["modelId"] = "dtmi:com:microsoft:akri:AdrBaseService;1";
                if (mqttClient.ClientId != null)
                {
                    TopicTokenMap["executorId"] = mqttClient.ClientId;
                }
                TopicTokenMap["commandName"] = "notifyOnAssetUpdate";
            }
        }
    }
}
