/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.Iot.Operations.Services.AssetAndDeviceRegistry.AdrBaseService
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using Azure.Iot.Operations.Services.AssetAndDeviceRegistry;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class NotifyOnAssetUpdateRequestSchema
    {
        /// <summary>
        /// The 'assetName' Field.
        /// </summary>
        [JsonPropertyName("assetName")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string? AssetName { get; set; } = default;

        /// <summary>
        /// The 'notificationMessageType' Field.
        /// </summary>
        [JsonPropertyName("notificationMessageType")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public NotificationMessageType? NotificationMessageType { get; set; } = default;

    }
}
