/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.Iot.Operations.Services.AssetAndDeviceRegistry.AdrBaseService
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using Azure.Iot.Operations.Services.AssetAndDeviceRegistry;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class Topic : IJsonOnDeserialized, IJsonOnSerializing
    {
        /// <summary>
        /// The 'path' Field.
        /// </summary>
        [JsonPropertyName("path")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public string Path { get; set; } = default!;

        /// <summary>
        /// The 'retain' Field.
        /// </summary>
        [JsonPropertyName("retain")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public Retain? Retain { get; set; } = default;

        void IJsonOnDeserialized.OnDeserialized()
        {
            if (Path is null)
            {
                throw new ArgumentNullException("path field cannot be null");
            }
        }

        void IJsonOnSerializing.OnSerializing()
        {
            if (Path is null)
            {
                throw new ArgumentNullException("path field cannot be null");
            }
        }
    }
}
