/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.Iot.Operations.Services.AssetAndDeviceRegistry.AdrBaseService
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using Azure.Iot.Operations.Services.AssetAndDeviceRegistry;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class TrustSettingsSchema : IJsonOnDeserialized, IJsonOnSerializing
    {
        /// <summary>
        /// The 'issuerList' Field.
        /// </summary>
        [JsonPropertyName("issuerList")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string? IssuerList { get; set; } = default;

        /// <summary>
        /// The 'trustList' Field.
        /// </summary>
        [JsonPropertyName("trustList")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string? TrustList { get; set; } = default;

        /// <summary>
        /// The 'trustMode' Field.
        /// </summary>
        [JsonPropertyName("trustMode")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public string TrustMode { get; set; } = default!;

        void IJsonOnDeserialized.OnDeserialized()
        {
            if (TrustMode is null)
            {
                throw new ArgumentNullException("trustMode field cannot be null");
            }
        }

        void IJsonOnSerializing.OnSerializing()
        {
            if (TrustMode is null)
            {
                throw new ArgumentNullException("trustMode field cannot be null");
            }
        }
    }
}
