/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.Iot.Operations.Services.AssetAndDeviceRegistry.AepTypeService
{
    using System;
    using System.Collections.Generic;
    using Azure.Iot.Operations.Protocol;
    using Azure.Iot.Operations.Protocol.RPC;
    using Azure.Iot.Operations.Protocol.Models;
    using Azure.Iot.Operations.Services.AssetAndDeviceRegistry;

    public static partial class AepTypeService
    {
        /// <summary>
        /// Specializes the <c>CommandInvoker</c> class for Command 'createDiscoveredAssetEndpointProfile'.
        /// </summary>
        public class CreateDiscoveredAssetEndpointProfileCommandInvoker : CommandInvoker<CreateDiscoveredAssetEndpointProfileRequestPayload, CreateDiscoveredAssetEndpointProfileResponsePayload>
        {
            /// <summary>
            /// Initializes a new instance of the <see cref="CreateDiscoveredAssetEndpointProfileCommandInvoker"/> class.
            /// </summary>
            public CreateDiscoveredAssetEndpointProfileCommandInvoker(ApplicationContext applicationContext, IMqttPubSubClient mqttClient)
                : base(applicationContext, mqttClient, "createDiscoveredAssetEndpointProfile", new Utf8JsonSerializer())
            {
                this.ResponseTopicPrefix = "clients/{invokerClientId}"; // default value, can be overwritten by user code

                TopicTokenMap["modelId"] = "dtmi:com:microsoft:akri:AepTypeService;1";
                if (mqttClient.ClientId != null)
                {
                    TopicTokenMap["invokerClientId"] = mqttClient.ClientId;
                }
                TopicTokenMap["commandName"] = "createDiscoveredAssetEndpointProfile";
            }
        }
    }
}
