/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */
#![allow(unused_imports)]

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use derive_builder::Builder;
use iso8601_duration::Duration;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::super::common_types::{b64::Bytes, date_only::Date, decimal::Decimal, time_only::Time};
use super::asset_stream_destination_schema_element_schema::AssetStreamDestinationSchemaElementSchema;

#[derive(Serialize, Deserialize, Debug, Clone, Builder)]
pub struct AssetStreamSchemaElementSchema {
    /// The 'destinations' Field.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub destinations: Option<Vec<AssetStreamDestinationSchemaElementSchema>>,

    /// The 'name' Field.
    pub name: String,

    /// The 'streamConfiguration' Field.
    #[serde(rename = "streamConfiguration")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub stream_configuration: Option<String>,

    /// The 'typeRef' Field.
    #[serde(rename = "typeRef")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub type_ref: Option<String>,
}
