/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */
#![allow(unused_imports)]

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use derive_builder::Builder;
use iso8601_duration::Duration;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::super::common_types::{b64::Bytes, date_only::Date, decimal::Decimal, time_only::Time};
use super::asset_management_group_action_type_schema::AssetManagementGroupActionTypeSchema;

#[derive(Serialize, Deserialize, Debug, Clone, Builder)]
pub struct AssetManagementGroupActionSchemaElementSchema {
    /// The 'actionConfiguration' Field.
    #[serde(rename = "actionConfiguration")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub action_configuration: Option<String>,

    /// The 'actionType' Field.
    #[serde(rename = "actionType")]
    pub action_type: AssetManagementGroupActionTypeSchema,

    /// The 'name' Field.
    pub name: String,

    /// The 'targetUri' Field.
    #[serde(rename = "targetUri")]
    pub target_uri: String,

    /// The 'timeOutInSeconds' Field.
    #[serde(rename = "timeOutInSeconds")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub time_out_in_seconds: Option<u32>,

    /// The 'topic' Field.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub topic: Option<String>,

    /// The 'typeRef' Field.
    #[serde(rename = "typeRef")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub type_ref: Option<String>,
}
