/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */
#![allow(unused_imports)]

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use derive_builder::Builder;
use iso8601_duration::Duration;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::super::common_types::{b64::Bytes, date_only::Date, decimal::Decimal, time_only::Time};
use super::details_schema_element_schema::DetailsSchemaElementSchema;

#[derive(Serialize, Deserialize, Debug, Clone, Builder)]
pub struct ConfigError {
    /// The 'code' Field.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub code: Option<String>,

    /// The 'details' Field.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub details: Option<Vec<DetailsSchemaElementSchema>>,

    /// The 'innerError' Field.
    #[serde(rename = "innerError")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub inner_error: Option<HashMap<String, String>>,

    /// The 'message' Field.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub message: Option<String>,
}
