/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */
#![allow(unused_imports)]

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use derive_builder::Builder;
use iso8601_duration::Duration;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::super::common_types::{b64::Bytes, date_only::Date, decimal::Decimal, time_only::Time};
use super::authentication_schema::AuthenticationSchema;
use super::trust_settings_schema::TrustSettingsSchema;

#[derive(Serialize, Deserialize, Debug, Clone, Builder)]
pub struct InboundSchemaMapValueSchema {
    /// The 'additionalConfiguration' Field.
    #[serde(rename = "additionalConfiguration")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub additional_configuration: Option<String>,

    /// The 'address' Field.
    pub address: String,

    /// The 'authentication' Field.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub authentication: Option<AuthenticationSchema>,

    /// The 'endpointType' Field.
    #[serde(rename = "endpointType")]
    pub endpoint_type: String,

    /// The 'trustSettings' Field.
    #[serde(rename = "trustSettings")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub trust_settings: Option<TrustSettingsSchema>,

    /// The 'version' Field.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub version: Option<String>,
}
