/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.Iot.Operations.Services.SchemaRegistry.SchemaRegistry
{
    using System;
    using Azure.Iot.Operations.Services.SchemaRegistry;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class SchemaRegistryErrorException : Exception
    {
        public SchemaRegistryErrorException(SchemaRegistryError schemaRegistryError)
            : base(schemaRegistryError.Message)
        {
            SchemaRegistryError = schemaRegistryError;
        }

        public SchemaRegistryError SchemaRegistryError { get; }
    }
}
