/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.Iot.Operations.Services.SchemaRegistry.SchemaRegistry
{
    using System.Runtime.Serialization;
    using System.Text.Json.Serialization;

    [JsonConverter(typeof(JsonStringEnumMemberConverter))]
    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public enum SchemaRegistryErrorTarget
    {
        [EnumMember(Value = @"Description")]
        DescriptionProperty = 0,
        [EnumMember(Value = @"DisplayName")]
        DisplayNameProperty = 1,
        [EnumMember(Value = @"Format")]
        FormatProperty = 2,
        [EnumMember(Value = @"Name")]
        NameProperty = 3,
        [EnumMember(Value = @"SchemaArmResource")]
        SchemaArmResource = 4,
        [EnumMember(Value = @"SchemaContent")]
        SchemaContentProperty = 5,
        [EnumMember(Value = @"SchemaRegistryResource")]
        SchemaRegistryArmResource = 6,
        [EnumMember(Value = @"SchemaType")]
        SchemaTypeProperty = 7,
        [EnumMember(Value = @"SchemaVersionArmResource")]
        SchemaVersionArmResource = 8,
        [EnumMember(Value = @"Tags")]
        TagsProperty = 9,
        [EnumMember(Value = @"Version")]
        VersionProperty = 10,
    }
}
